name: Create Ghidra plugin Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Release Version"
        required: true
        type: string
        pattern: '^\d+\.\d+\.\d+$'

permissions:
  contents: write

jobs:
    createrelease:
      name: Build
      runs-on: [ubuntu-latest]
      steps:
        - name: Checkout Development Repo
          uses: actions/checkout@v4

        - name: Create unknowncyberghidraplugin.tgz File
          working-directory: ./UnknownCyberPlugin
          run: |
            mkdir unknowncyber
            cp -r extension.properties lib LICENSE.txt Module.manifest ./unknowncyber/
            zip ./unknowncyber/lib/UnknownCyberPlugin-src.zip src/*
            tar czvf unknowncyberghidraplugin.tgz unknowncyber
            sha256sum unknowncyberghidraplugin.* > checksum

        - name: Release
          uses: softprops/action-gh-release@v2
          with:
            files: unknowncyberghidraplugin.tgz
            name: "UnknownCyber Ghidra Plugin"
            tag_name: ${{github.event.inputs.version}}
